<?php
/**
 * Generate Search Form
 *
 * Provides the search form generated by get_search_form().
 *
 */
global $fup_search_form_count;
$fup_search_form_count++;
?>
<div class="search-form-container">
	<form class="form-search" action="<?php echo home_url( '/' ); ?>">
		<fieldset>
			<legend><?php _e( 'Looking for something specific?', 'fup' );
				?></legend>
			<div class="form-group">
				<label for="search_input_<?php echo $fup_search_form_count;
					?>" class="screen-reader"><?php
					_e( 'Search for it: ', 'fup' ); ?></label>
				<?php if ( TRUE == FALSE ): ?>
				<input id="search_input_<?php echo $fup_search_form_count;
					?>" type="search" class="form-control" name="s"
					value="" placeholder="<?php
					esc_attr_e( 'What\'s your interest?', 'fup' );
					?>" results="5">
				<?php endif; ?>
				<input id="search_input_<?php echo $fup_search_form_count;
					?>" type="text" class="form-control" name="s"
					value="" placeholder="<?php
					esc_attr_e( 'What\'s your interest?', 'fup' );
					?>">
			</div>
			<div class="text-center">
				<button type="submit" class="btn btn-default"
					value="Search"><?php _e( 'Search it!' , 'fup' );
					?></button>
			</div>
		</fieldset>
	</form>
</div>
